spring.application.name=ecommerce-api

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres
spring.datasource.username=${SUPABASE_USER}
spring.datasource.password=${SUPABASE_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_batch_fetch_size=20
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app.jwtSecret=kE256lGqL12qU81I0pP9bQoM3g9xT7JmFhZcRdA3pW8=
app.jwtIssuer=EcommerceAPI
app.jwtAudience=EcommerceUsers
app.jwtExpirationHours=2

paypal.client.id=AX92WcQnbfBqWufIRr4jtxerAyK4bfjIQmtBC9DI0uEAVa_uhMMuFg8DLVz4pwIqgvEqChQmKJjwTbXs
paypal.client.secret=EKFvX4EXqNDM0kThFWDpEkQVusX0uE_mK5OWXOSpiNl812INhlAzKf__ZNgk05d2v6coIyOz2SDIKPOA
paypal.api.base=https://api-m.sandbox.paypal.com
paypal.webhook.id=31846768MB569482E